# Generated by Django 4.1.6 on 2023-02-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_to_do_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='text',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текстовое поле'),
        ),
        migrations.AlterField(
            model_name='to_do',
            name='execution_date',
            field=models.CharField(blank=True, help_text='Введите в формате ГГГГ-ММ-ДД', max_length=10, null=True, verbose_name='Дата исполнения'),
        ),
    ]
